version: 2
jobs:
  build:
    docker:
      - image: circleci/node:carbon
    working_directory: ~/repo

    steps:
      - checkout:
          post:
          - git checkout blog

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
