version: 2
jobs:
  build:
    docker:
      - image: circleci/node:carbon-browsers
    working_directory: ~/repo

    steps:
      - checkout:
          post:
          - git checkout blog

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Workaround for GoogleChrome/puppeteer#290
          command: 'sh .circleci/setup_puppeteer.sh'

      - run: yarn install

      - run: yarn build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
     
  test:
    docker:
      - image: circleci/node:carbon-browsers
    working_directory: ~/repo

    steps:
      - checkout:
          post:
          - git checkout blog

      - run: yarn test          

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
